# config/config.yaml
paths:
  data_dir: "./data"
  crawled_reviews_dir: "./data/crawled_reviews"
  preprocessed_dir: "./data/preprocessed"
  embedding_dir: "./data/embedding_matrics"
  prompt_dir: "./prompt"
  final_outputs_dir: "../final_outputs"

  aste_dir: "./data/aste"
  train_dir: "./data/aste/train"
  eval_dir: "./data/aste/eval"
  inference_dir: "./data/aste/inference"

pipeline:
  sft:
    review_crawling: false        # 크롤링은 별도 실행 (예, 테스트 시 False)
    review_preprocessing: true
    train_data_sampling: false    # train data 생성시에만 별도 실행
    train_data_annotating: false  # train data 생성시에만 별도 실행
    sft: true                    # SFT는 파일로 별도 실행
  review:
    aste_inference: true         # inference 별도 실행
    review_summarization: true
    keyword_recommendation: true


# Train Data Annotation 관련
train_data_annotating:
  num_train_data: 900
  annotation_model: "gpt-4o"

# Inference 관련
inference_data: "deepseek_inference.csv"