services:
  mysql:
    image: mysql:8-oracle
    container_name: foodly_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "nlp_ai_shopper_T734"
      MYSQL_DATABASE: foodly
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: